development:
  adapter: postgresql
  database: my_blog_development
  pool: 5
  timeout: 5000
  host: localhost
test:
  adapter: postgresql
  database: my_blog_test
  pool: 5
  timeout: 5000
  host: localhost
production:
  adapter: postgresql
  database: my_blog_production
  pool: 5
  timeout: 5000
  host: localhost
